Get test meetings
Metro-Records/scrapers-lametro pull request #1
Opened 2023-03-10 20:46 UTC by xmedr

## Overview

As per [`la-metro-councilmatic` issue #492](https://github.com/Metro-Records/la-metro-councilmatic/issues/942), new meeting body types have been created, but were not being included by the scraper. This brings those in.

## Testing Instructions
- Run the scraper as normal
- Check to see if those new meeting bodies were included

2023-03-10 20:48 UTC, xmedr commented
Only question I have is, there's a line that assigns a classification to these bodies, and as of now they are all being categorized as `committee`'s. Should this still be true for the ones titled "Primary Legislative Body"?

2023-03-13 11:29 UTC, hancush requested changes
Hey, @xmedr – If we wanted to expand the range of body types we scrape, this would be the right solution, but that's not what we talked about. We discussed keeping the original body types, and instead adding and `or` clause that tested for the name of the body against the name of the test organization. Can you go back and make that edit?

2023-03-13 11:29 UTC, hancush commented on lametro/people.py
> +            if body['BodyTypeId'] in body_types_list:
```suggestion
            if body['BodyTypeId'] in body_types_list ++or body name matches test body ++:
```

2023-03-13 15:32 UTC, xmedr commented
@hancush Oooh, I see I see! So if I'm understanding this better now, checking for bodies that contain 'test' in their name would be what we're looking for here. That seems to be working.

> against the name of the body against the name of the test organization

Or would we rather have an exact match, based off this?

2023-03-14 14:52 UTC, hancush approved these changes
Better!

2023-03-14 14:56 UTC, merged