Send duplicate agenda item exception to Sentry
Metro-Records/scrapers-lametro pull request #15
Opened 2024-05-14 20:11 UTC by antidipyramid

# Overview

See title.

Connects #14

2024-06-05 19:43 UTC, hancush requested changes
Couple of things inline.

2024-06-05 19:43 UTC, hancush commented on lametro/events.py
> +                try:
Will this also skip scraping the event with the funky agenda?

2024-06-05 19:43 UTC, hancush commented on tests/test_events.py
> -def test_sequence_duplicate_error(event_scraper,
What about testing that the (mock) alert is sent, rather than removing this test?

2024-07-17 15:20 UTC, antidipyramid commented on lametro/events.py
> +                try:
No, the scraper should yield out the event after sending a Sentry alert.

2024-07-17 15:52 UTC, hancush approved these changes
Nice, @antidipyramid. Let's bring this in.

2024-07-17 15:52 UTC, hancush commented on lametro/events.py
> +                try:
So the effect is that the yielded event won't have an associated agenda, i.e., the event will show up on the board agendas site sans agenda, until the duplicate is fixed? I think that should be ok, but we should let Metro know.

2024-07-18 19:51 UTC, merged