Alert sentry when no attachments found for approved minutes
Metro-Records/scrapers-lametro pull request #34
Opened 2024-11-15 21:52 UTC by xmedr

## Overview

This pr will alert sentry when an approved minutes matter is missing any attachments, provide details to examine it within legistar, and continue the scrape without failing outright

- Connects #24 

## Testing Instructions

 * Check the following test alert in sentry (or trigger your own, read on for details) and confirm that it gives enough details on the situation to be actionable
   * [Sentry Alert](https://datamade.sentry.io/issues/6067789974/?project=4504447849201664&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=90d&stream_index=1)
 * To trigger your own alert:
   * pull down this branch, and insert a breakpoint after line 596 of events.py (after the `capture_exception` command)
   * after line 553, reassign the attachments var to an empty list
   * Run a big enough scrape to get a matter with potential attachments. I ran `docker-compose run --rm scrapers pupa update lametro events window=200 --rpm=0`
   * Once you hit the breakpoint, check sentry for the new alert

2024-11-26 21:15 UTC, antidipyramid requested changes

2024-11-26 21:15 UTC, antidipyramid commented on lametro/events.py
> +                    raise MissingAttachmentsException(matter["MatterId"], attachment_url)
Multiple indentation levels can make code more difficult to read. What do you think about doing something like:

```py
for matter in result:
...
    try:
        if len(attachments) == 0:
            raise MissingAttachmentsException(matter["MatterId"], attachment_url)
    except MissingAttachmentsException as e:
        capture_exception(e)
        continue

    if len(attachments) == 1:
    ...
```

2024-12-02 19:40 UTC, xmedr commented on lametro/events.py
> +                    raise MissingAttachmentsException(matter["MatterId"], attachment_url)
Ah I see what you mean, you're totally right!

2025-01-07 14:25 UTC, antidipyramid approved these changes

2025-01-07 15:57 UTC, merged